name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7]
    # runs-on: windows-latest
    # runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: {{ matrix.python-version }}
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-04-09
        override: true
    - name: "Show rustc version"
      run: rustc --version
    - run: pip install maturin
    - run: maturin build --release --manifest-path ../Cargo.toml --cargo-extra-args='--features python' --interpreter python${{ matrix.python-version }}
      working-directory: ./py


