name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.44.0
        override: true
    - name: "Show rustc version"
      run: rustc --version
    - name: Run cargo test
      run: pip install .


